---
- name: Playbook for Upgrading kernel
  hosts: "{{host}}"
  become: yes
  become_method: sudo
  tasks:
    - name: register
      shell: uname -r
      register: message
    - name: Debug
      debug:
        msg: "{{message}}"

    - name: upgrade kernel
      package: 
        name: kernel
        state: latest

    - name: Reboot server
      command: /sbin/reboot

    - name: Wait for the server to finish rebooting
      sudo: no
      local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=300

    
    - name: register
      shell: uname -r
      register: message
      
    - name: Debug
      debug:
        msg: "{{message}}"


